# PACMAN
- name: Install Pacman Packages
  pacman:
    name:
      # Microcode
      - amd-ucode
      - intel-ucode

      # System
      - base
      - base-devel
      - polkit-gnome
      - clamtk
      - qt5ct
      - reflector
      - ufw
      - xdg-user-dirs
      - udiskie

      # Android
      - android-file-transfer
      - android-tools
      - scrcpy

      # WM
      - hyprland
      - hyprlock
      - hypridle
      - hyprpicker
      - wev
      - swaync
      - satty
      - waybar
      - wl-clipboard
      - xdg-desktop-portal-hyprland
      - kitty
      - rofi-wayland

      # File Manager
      - yazi
      - nemo
      - nemo-fileroller
      - nemo-image-converter

      # Fonts
      - ttf-font-awesome
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
      - ttf-jetbrains-mono-nerd

      # Tools
      - baobab
      - cliphist
      - galculator
      - gnome-logs
      - gparted
      - playerctl
      - slurp
      - grim
      - nm-connection-editor
      - xwaylandvideobridge
      - gnome-keyring
      - protonmail-bridge

      # Bluetooth
      - bluez

      # CLI / TUI
      - bat
      - btop
      - eza
      - fd
      - fzf
      - nvtop
      - duf
      - dua-cli
      - ripgrep
      - ripgrep-all
      - sd
      - jq
      - fastfetch

      # Productivity
      - libreoffice-fresh
      - obsidian
      - thunderbird
      - zathura
      - zathura-pdf-mupdf

      # Multimedia
      - geeqie
      - imagemagick
      - mpv
      - pavucontrol
      - wine
      - winetricks

# AUR
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"

- name: Install AUR Packages
  become: true
  become_user: aur_builder
  aur:
    use: yay
    name:
      # Browser
      - brave-bin
      - zen-browser-avx0-bin

      # WM
      - swayosd-git
      - swww
      - nwg-displays
      - nwg-look
      - pyprland
      - waybar-updates

      # Hooks
      - check-broken-packages-pacman-hook-git
      - reflector-pacman-hook-git
      - sync-pacman-hook-git
      - needrestart
      - paccache-hook

      # Bluetooth
      - overskride

      # CLI / TUI
      - cava
      - pacseek
      - gtrash-bin
      - sysz
      - topgrade
      - tgpt-bin

      # Tools
      - auto-cpufreq
      - devify
      - upscayl-bin
      - downgrade
      - android-sdk-platform-tools
      - pika-backup
      - rar

      # Theme
      - catppuccin-gtk-theme-macchiato
      - catppuccin-cursors-macchiato
      - ttf-ms-win11-auto

      # Multimedia
      - vesktop-bin
