# PACMAN
- name: Install Pacman Packages
  pacman:
    name:
      # Web
      - yarn
      - npm
      - nodejs

      # Python
      - python-pip
      - python-pipx

      # Rust
      - rustup

      # Go
      - go

      # Lua
      - lua
      - luarocks

      # Tools
      - github-cli
      - dbeaver
      - git-delta
      - lazygit
      - onefetch
      - tmux

      # Neovim
      - neovide
      - bob
      - vim

# AUR
- name: Install AUR Packages
  become: true
  become_user: aur_builder
  aur:
    use: yay
    name:
      - lazynpm
      - scc-bin
      - tgpt-bin
      - vscodium-bin
      - vscodium-marketplace-bin
      - mise-bin

# Cargo
- name: Install Rust Packages
  cargo:
    name:
      - cargo-update
      - cargo-binstall

# Npm
- name: Install Npm Packages
  npm:
    name:
      - commitizen
      - cz-git
    global: true
