# PACMAN
- name: Install Pacman Packages
  pacman:
    name:
      # Audio
      - easyeffects
      - gst-plugins-base
      - lsp-plugins
      - qpwgraph

      # Video
      - obs-studio
      - blender

      # Image
      - pinta
      - krita

      # Downloaders
      - yt-dlp

- name: Install AUR Packages
  become: true
  become_user: aur_builder
  aur:
    use: yay
    name:
      # Audio
      - spicetify-cli
      - spotify

      # Downloaders
      - gallery-dl
      - spotdl
